Trying to improve runtime builds and testing in linux.

diff --git a/.github/workflows/docker-hub.yml b/.github/workflows/docker-hub.yml
--- a/.github/workflows/docker-hub.yml
+++ b/.github/workflows/docker-hub.yml
@@ -8,7 +8,6 @@ on:
   push:
     branches:
       - master
-      - develop
     tags:
       - 'v*.*.*'
 
@@ -45,6 +44,9 @@ jobs:
             bash ./docker-compose.sh push
           elif [[ "${{ contains(github.ref, 'refs/tags/') }}" = true ]]; then
             bash ./docker-compose.sh version
+          else
+            echo "Failed to push the docker images"
+            exit 1
           fi
 
       - name: Logout from DockerHub
